name: Publish Release

on:
  push:
    tags:
      - '*'

env:
  GITHUB_TARGET_REPO: "https://maven.martmists.com/releases"
  DEPLOY_TYPE: "release"
  DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

jobs:
  build-jvm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Run tests
        run: ./gradlew :commons-jvm:test :commons-gradle:test

      - name: Publish to Maven
        run: ./gradlew :commons-jvm:publish :commons-gradle:publish


  build-mpp:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'

      - uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan

      - name: Run tests
        run: ./gradlew :commons-mpp:allTests

      - name: Publish to Maven
        run: ./gradlew :commons-mpp:publish
